version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  build:
    commands:
      - bash ./build_docker_image.sh
  post_build:
    commands:
      - bash ./push_to_ecr.sh
artifacts:
  files: imagedefinitions.json